"""Central constants and configuration keys."""

# Settings keys
STREAM_MODE = "STREAM_MODE"  # HLS | WEBRTC
STREAM_RES = "STREAM_RES"  # e.g. 1280x720
STREAM_FPS = "STREAM_FPS"
RECORD_RES = "RECORD_RES"  # e.g. 1920x1080
RECORD_FPS = "RECORD_FPS"
VIDEO_SOURCE = "VIDEO_SOURCE"
AUDIO_SOURCE = "AUDIO_SOURCE"
STREAM_UDP_URL = "STREAM_UDP_URL"
MOTION_SOURCE = "MOTION_SOURCE"
VIDEO_ROTATION = "VIDEO_ROTATION"  # 0, 90, 180, 270
HLS_SEGMENT_SECONDS = "HLS_SEGMENT_SECONDS"
HLS_PLAYLIST_SIZE = "HLS_PLAYLIST_SIZE"
PREFIX = "PREFIX"
PHOTO_INTERVAL_S = "PHOTO_INTERVAL_S"
TIMELAPSE_FPS = "TIMELAPSE_FPS"
TIMELAPSE_DAYS = "TIMELAPSE_DAYS"
UPLOAD_INTERVAL_MIN = "UPLOAD_INTERVAL_MIN"
RETENTION_DAYS = "RETENTION_DAYS"
YOLO_MODEL_PATH = "YOLO_MODEL_PATH"
YOLO_THRESH = "YOLO_THRESH"
IR_GPIO = "IR_GPIO"
LUX_GPIO = "LUX_GPIO"
LUX_THRESHOLD = "LUX_THRESHOLD"
LOG_ENABLED = "LOG_ENABLED"
LOG_LEVEL = "LOG_LEVEL"
MOTION_ENABLED = "MOTION_ENABLED"
MOTION_THRESHOLD = "MOTION_THRESHOLD"
MOTION_DURATION_S = "MOTION_DURATION_S"
MOTION_COOLDOWN_S = "MOTION_COOLDOWN_S"
MOTION_SENSOR_GPIO = "MOTION_SENSOR_GPIO"
MOTION_SENSOR_ENABLED = "MOTION_SENSOR_ENABLED"
MOTION_FRAMEDIFF_ENABLED = "MOTION_FRAMEDIFF_ENABLED"
MOTION_SERVICE_ENABLED = "MOTION_SERVICE_ENABLED"

# HiDrive upload settings
HIDRIVE_USER = "HIDRIVE_USER"
HIDRIVE_PASSWORD = "HIDRIVE_PASSWORD"
HIDRIVE_TARGET_DIR = "HIDRIVE_TARGET_DIR"
UPLOAD_PHOTOS = "UPLOAD_PHOTOS"
UPLOAD_VIDEOS = "UPLOAD_VIDEOS"
UPLOAD_TIMELAPSES = "UPLOAD_TIMELAPSES"
UPLOAD_RETENTION_DAYS = "UPLOAD_RETENTION_DAYS"
UPLOAD_START_HOUR = "UPLOAD_START_HOUR"
UPLOAD_END_HOUR = "UPLOAD_END_HOUR"

# WiFi fallback settings
WIFI_SSID = "WIFI_SSID"
WIFI_PASSWORD = "WIFI_PASSWORD"

# Bird detection settings
DETECTION_START_HOUR = "DETECTION_START_HOUR"
DETECTION_END_HOUR = "DETECTION_END_HOUR"

# Day/Night mode settings
DAY_NIGHT_ENABLED = "DAY_NIGHT_ENABLED"
DAY_NIGHT_THRESHOLD = "DAY_NIGHT_THRESHOLD"
DAY_NIGHT_CHECK_INTERVAL = "DAY_NIGHT_CHECK_INTERVAL"

# API / security
CSRF_COOKIE_NAME = "birdshome_csrf"
CSRF_HEADER_NAME = "X-CSRF-Token"
SESSION_COOKIE_NAME = "birdshome_session"

# Stream modes
MODE_HLS = "HLS"
MODE_WEBRTC = "WEBRTC"
